timely:
  # 是否开启
  switch: true
  # 偏移量文件 在项目根目录下
  offset-file-name: /offset-name
  # 是否启东时清除偏移量文件
  offset-file-clean: true
  # 偏移量提交时间 单位ms
  offset-time: 1
  # 读取历史记录文件
  history-file-name: /offset-name/dbhistory.dat
  # 读取的数据库信息
  offline:
    ip: 192.168.99.125
    port: 5237
    username: v3_ds1
    password: v3_ds1
    # 保证每个数据库读取的 instance-name  logic-name 不能相同
    # 实例名
    instance-name: V3_DS1
    # 逻辑名
    logic-name: V3_DS1
    # 读取的表
    include-table: V3_DS1.EMP
    # 读取的库
    include-db: V3_DS1
