timely:
  # 是否开启
  switch: true
  # 偏移量文件
  offset-file-name: E://test/mysql/offsets.dat
  # 是否启东时清除偏移量文件
  offset-file-clean: true
  # 偏移量提交时间 单位ms
  offset-time: 1
  # 读取历史记录文件
  history-file-name: E://test/mysql/dbhistory.dat
  # 读取的数据库信息
  offline:
    ip: 127.0.0.1
    port: 3306
    username: root
    password: 123qwe
    # 保证每个数据库读取的 instance-name  logic-name 不能相同
    # 实例名
    instance-name: db01
    # 逻辑名
    logic-name: db01
    # 读取的表
    include-table: db01.system_dept
    # 读取的库
    include-db: db01

